"""empty message

Revision ID: 28bb592422a9
Revises: 
Create Date: 2019-12-10 21:02:38.630252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bb592422a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('Users', 'created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Users', 'first',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('Users', 'last',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'last',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('Users', 'first',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('Users', 'created',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('Users', 'active')
    # ### end Alembic commands ###
