"""empty message

Revision ID: 2cb29f79f741
Revises: 
Create Date: 2019-11-29 21:47:32.587719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb29f79f741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=128), nullable=False),
    sa.Column('last', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_points'), 'user', ['points'], unique=False)
    op.create_index(op.f('ix_user_qualified'), 'user', ['qualified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_qualified'), table_name='user')
    op.drop_index(op.f('ix_user_points'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
