"""empty message

Revision ID: 3462d6c8ec26
Revises: 
Create Date: 2019-12-26 15:21:24.155628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3462d6c8ec26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_points'), 'Users', ['points'], unique=False)
    op.create_index(op.f('ix_Users_qualified'), 'Users', ['qualified'], unique=False)
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_index('ix_Users_points', table_name='Users')
    op.drop_index('ix_Users_qualified', table_name='Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Users_qualified', 'Users', ['qualified'], unique=False)
    op.create_index('ix_Users_points', 'Users', ['points'], unique=False)
    op.create_index('ix_Users_email', 'Users', ['email'], unique=1)
    op.drop_index(op.f('ix_Users_qualified'), table_name='Users')
    op.drop_index(op.f('ix_Users_points'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    # ### end Alembic commands ###
