"""empty message

Revision ID: 5482c2a28b53
Revises: 
Create Date: 2019-12-09 21:06:43.192236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5482c2a28b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'first',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('Users', 'last',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'last',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('Users', 'first',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
