"""empty message

Revision ID: adc9153eb51e
Revises: 359cbe86e0c3
Create Date: 2019-12-17 19:41:59.923752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc9153eb51e'
down_revision = '359cbe86e0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('department', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_points'), 'Users', ['points'], unique=False)
    op.create_index(op.f('ix_Users_qualified'), 'Users', ['qualified'], unique=False)
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_index('ix_Users_points', table_name='Users')
    op.drop_index('ix_Users_qualified', table_name='Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Users_qualified', 'Users', ['qualified'], unique=False)
    op.create_index('ix_Users_points', 'Users', ['points'], unique=False)
    op.create_index('ix_Users_email', 'Users', ['email'], unique=1)
    op.drop_index(op.f('ix_Users_qualified'), table_name='Users')
    op.drop_index(op.f('ix_Users_points'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_column('Users', 'department')
    # ### end Alembic commands ###
